language: python

cache:
  directories:
  - $HOME/.cache/pip

python:
  - "3.8"

install:
  # install miniconda
  - deactivate
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
  - MINICONDA_PATH=/home/travis/miniconda3
  - chmod +x miniconda.sh && ./miniconda.sh -b -p $MINICONDA_PATH
  - chmod +x $MINICONDA_PATH
  - export PATH=$MINICONDA_PATH/condabin:$PATH
  - conda update --yes conda
  # create the testing environment
  - make create_environment
  - conda init bash
  - conda activate reproallthethings
  - make update_environment

script:
  - pwd
  - ls -la
  - cd src
  - pytest --doctest-modules --doctest-continue-on-failure --verbose --cov --junitxml=test-reports/junit.xml

after_success:
  - coveralls