name: embedallthethings2
dependencies:
  - pip
  - pip:
    - -e .  # conda >= 4.4 only
    - python-dotenv>=0.5.1
    - nbval
    - nbdime
    - datashader
    - holoviews
    - umap-learn>=0.4.0rc1
  - setuptools
  - wheel
  - sphinx
  - click
  - coverage
  - pytest-cov
  - jupyter
  - scikit-learn
  - joblib
  - nb_conda
  - pandas
  - requests
  - pathlib
  - python=3.8
  - seaborn
  - bokeh

