name: reproallthethings
channels:
  - defaults
dependencies:
  - pip
  - pip:
    - -e .  # conda >= 4.4 only
    - python-dotenv>=0.5.1
    - nbval
    - nbdime
    - bokeh!=2.4.0
    - datashader
    - holoviews
    - enstop
    - coveralls
    - git+https://github.com/TutteInstitute/vectorizers.git
    - git+https://github.com/TutteInstitute/TextMAP.git
    - gdown
  - setuptools
  - wheel
  - git>=2.5  # for git worktree template updating
  - sphinx
  - bokeh!=2.4.0
  - click
  - colorcet
  - coverage
  - coveralls
  - matplotlib
  - jupyter
  - scikit-learn
  - scipy
  - joblib
  - nb_conda_kernels#<2.2.0  # nb_conda_kernels issue #158
  - pandas
  - requests
  - pathlib
  - seaborn
  - nltk
  - numba
  - fsspec
  - python=3.7
  - conda-forge::hdbscan
  - conda-forge::umap-learn
  - conda-forge::rich
