ARCH := $(shell arch)
CONDA_EXE ?= /Users/amywooding/miniconda3/condabin/conda
MODULE_NAME := src
PROJECT_DIR := $(shell dirname $(realpath $(lastword $(MAKEFILE_LIST))))
PROJECT_NAME := reproallthethings
PYTHON_INTERPRETER := python3
VIRTUALENV := conda
